Add the k6 package
GovTechSG/cicd-images pull request #64
Opened 2022-12-02 09:58 UTC by guruprasathv

2022-12-05 08:10 UTC, rameshbaskar requested changes

2022-12-05 08:10 UTC, rameshbaskar commented on k6/Dockerfile
> +FROM cypress/browsers:node14.15.0-chrome96-ff94
Can just use the standard `alpine node` image instead of Cypress image? Since this is just for K6, we don't actually need the Chrome and Firefox browsers right? So I guess a standard alpine node base image should work right?

2022-12-05 08:10 UTC, rameshbaskar commented on k6/.publish.sh
> +VERSION_FIREFOX=$(printf "${VERSIONS}" | grep firefox | cut -f 2 -d ':');
The Chrome and Firefox are not required for K6 right?

2022-12-05 08:10 UTC, rameshbaskar commented on k6/version-info
> +printf "firefox:${VERSION_FIREFOX}\n";
Can remove this as this is not relevant for K6?

2022-12-05 09:47 UTC, rameshbaskar approved these changes

2022-12-07 06:09 UTC, boonsiangteh approved these changes

2022-12-07 07:53 UTC, merged